# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]

name: test-renv

jobs:
  test-renv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - id: renv-lock
        run: |
          const fs = require("fs");
          fs.readFile("./renv.lock", "utf8", (err, data) => {
            if (err) {
              console.log("File read failed:", err);
              return;
            }
            console.log("File data:", data);
            renv_lock = JSON.parse(data);
            console.log(renv_lock.R.Version);
            console.log("::notice::" + renv_lock.R.Version);
            console.log("::set-output name={r-version}::" + renv_lock.R.Version);
          })
        shell: node {0}
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: steps.renv-lock.r-version
      - uses: r-lib/actions/setup-renv@master
