# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: [push, pull_request]

name: test-renv

jobs:
  test-renv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
         console.log("hello world")
        shell: node {0}
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-renv@master
